### ISSUE TITLE
Question about release

### ISSUE THREAD

**Issue by chadyred** [synolia/SyliusGDPRPlugin#26]
Hello,

How your release works ? Manually ? :)

Thanks

**Comment by oallain** [comment]
Hello,

Yes, i do it manually.
I was just waiting for PR #25 before creating a new release 😉

**Comment by oallain** [comment]
@chadyred new version is released see [Version 1.1.0](https://github.com/synolia/SyliusGDPRPlugin/releases/tag/v1.1.0)

Regards

**Comment by chadyred** [comment]
Thanks a lot :)
