### ISSUE TITLE
[Feature] Add confirmation before anonymisation

### ISSUE THREAD

**Issue by maximehuran** [synolia/SyliusGDPRPlugin#32]
Actually if I click on `Anonymise` button, I don't have confirmation.

<img width="187" alt="image" src="https://user-images.githubusercontent.com/11380627/149157004-5a02844a-b1f0-4353-85a1-f719371b87f0.png">

It could be nice to have a confirmation before like this : 

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/11380627/149157053-4af4ddaa-f37d-4433-bcde-5e3a81b7937d.png">

**Comment by GalloisLuca** [comment]
Hello @maximehuran !
Thanks for your proposition, it would be a nice feature to add !
If you want to add the feature feel free to do it ! :D If you don't, i will take time in the next weeks

**Comment by maximehuran** [comment]
I will try to do it 🙏
