### ISSUE TITLE
[Bug] Missing language key 

### ISSUE THREAD

**Issue by Geolim4** [synolia/SyliusGDPRPlugin#39]
**Describe the bug**
In `\Synolia\SyliusGDPRPlugin\Menu\GDPRMenuListener::addGDPRMenuItems` the child with `app.ui.gdpr.advanced_actions` language key does not exist.

**Expected behavior**
You may want to replace it by `sylius.ui.admin.synolia_gdpr.advanced_actions.title`

**Screenshots**
![Capture d’écran de 2022-06-13 14-32-10](https://user-images.githubusercontent.com/1332071/173354301-4cb82ab3-3036-434a-ba49-396f3ae6ebf5.png)

**Comment by Geolim4** [comment]
My bad, fixed in #37 can you please make a new release @oallain ? :D

**Comment by oallain** [comment]
Hello,
Yes, i'll make it asap.

**Comment by Geolim4** [comment]
Much appreciated, thanks !

**Comment by oallain** [comment]
Hello @Geolim4 

It's done on [v1.2.1](https://github.com/synolia/SyliusGDPRPlugin/releases/tag/v1.2.1)

**Comment by Geolim4** [comment]
Thank you very much!
