### ISSUE TITLE
[Bug] Exporting data from a customer with a cart result in an error

### ISSUE THREAD

**Issue by Kiwikoti** [synolia/SyliusGDPRPlugin#57]
Exporting customer data that have a cart will result in an error.

**Steps to reproduce the behavior:**
1. Connect to a user account
2. Add a product to the cart
3. Go to the admin to the customer page of the customer of step 1
4. Click on the button to export the data
5. See error

**Expected behavior**
The file with the exported data to be downloaded

**Screenshots**
![Capture d’écran 2023-07-19 à 18 15 31](https://github.com/synolia/SyliusGDPRPlugin/assets/111362284/9d196af2-d379-4247-81e9-e9dbc7b20916)

![Capture d’écran 2023-07-19 à 18 15 42](https://github.com/synolia/SyliusGDPRPlugin/assets/111362284/ab79745f-d63c-46a2-a85d-d99e8cb5dffd)

https://github.com/synolia/SyliusGDPRPlugin/assets/111362284/95159d6c-1642-4b04-b517-82d33165f164

**Additional context**
Sylius version: 1.12.8
Symfony version: 6.3.1

It looks like there is an issue when normalizing the data of an order in a cart state because the order entity does not have yet a tokenValue : 
`Parameter "tokenValue" for route "api_orders_admin_get_item" must match "[^/]++" ("" given) to generate a corresponding URL.`

**Comment by oallain** [comment]
Hello @etienne-monsieurbiz ,

Fixed and tagged [v1.5.1](https://github.com/synolia/SyliusGDPRPlugin/releases/tag/v1.5.1)

Thanks for reported.
