### ISSUE TITLE
[Bug] Latest PR #52 introduced side effect Call to a member function getCallable() on bool 

### ISSUE THREAD

**Issue by Geolim4** [synolia/SyliusGDPRPlugin#58]
**Describe the bug**
When checking customer profil in admin area got the following error:
Call to a member function getCallable() on bool.
Faulty code:
`        if ($function !== null && is_callable($function->getCallable())) {` in GdprExtension.php

This extension is directly related to sylius_plus, but in vanilla sylius, this twig extension does not exists.

**To Reproduce**
Go to /admin/customers/xxxxx

**Expected behavior**
No error

**Screenshots**
Error 500

**Additional context**

**Comment by oallain** [comment]
Hello @Geolim4 ,

Fixed and tagged [v1.5.1](https://github.com/synolia/SyliusGDPRPlugin/releases/tag/v1.5.1)

Thanks for reported.

**Comment by Geolim4** [comment]
Great, thank you !
